const char *page = "<!DOCTYPE html>"
"<html lang=\"zh-CN\">"
"<head>"
"<meta charset=\"UTF-8\" />"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />"
"<title>Magic-Mini 调光控制</title>"
"<style>"
"* {margin: 0; padding: 0; box-sizing: border-box; font-family: \"Arial\", \"华文细黑\";}"
"body {min-height: 100dvh; max-width: 100vw; padding: 20px;}"
".container {margin: 0 auto; width: 100%; padding: 20px; max-width: 450px;}"
"h1 {text-align: center; color: rgb(0, 123, 255); margin: 10px 0 20px 0; font-size: 24px;}"
".color-wheel-container {position: relative; width: 100%; padding-top: 100%; margin-bottom: 30px;}"
"#colorWheel {position: absolute; top: 0; left: 0; width: 100%; height: 100%; border-radius: 50%; box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.2);}"
"#colorSelector {position: absolute; width: 20px; height: 20px; border: 2px solid white; border-radius: 50%; box-shadow: 0 0 5px rgba(0, 0, 0, 0.5); transform: translate(-50%, -50%); cursor: grab; user-select: none;}"
"#colorSelector:active {cursor: grabbing;}"
".current-color {width: 100%; height: 60px; border-radius: 8px; margin-bottom: 20px; display: flex; align-items: center; justify-content: center; color: white; font-size: 16px; font-weight: bold; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.7);}"
".controls {display: flex; flex-direction: column; gap: 15px;}"
"button {border: none; border-radius: 8px; font-weight: bold; cursor: pointer; padding: 12px; font-size: 14px;}"
"#setColorBtn {background-color: rgb(0, 123, 255); color: white;}"
"#dialog {position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); width: 150px; height: 150px; border: none; outline: none; border-radius: 12px; background-color: rgba(0, 0, 0, 0.3); color: white;}"
"#dialogMessage {font-size: 16px; font-weight: bold; text-align: center; line-height: 150px;}"
"</style>"
"</head>"
"<body>"
"<div class=\"container\">"
"<h1>Magic-Mini 调光控制</h1>"
"<div class=\"color-wheel-container\">"
"<canvas id=\"colorWheel\"></canvas>"
"<div id=\"colorSelector\"></div>"
"</div>"
"<div class=\"current-color\" id=\"currentColor\">RGB(0, 0, 0)</div>"
"<div class=\"controls\">"
"<button id=\"setColorBtn\">应用颜色</button>"
"</div>"
"</div>"
"<dialog id=\"dialog\">"
"<p id=\"dialogMessage\">message</p>"
"</dialog>"
"<script>"
"let canvas, ctx; "
"let colorWheel, colorSelector, currentColor; "
"let setColorBtn; "
"let isDragging = false; "
"let centerX, centerY, radius; "
"let deviceAddress = \"magic-mini.local\"; "
"let isConnected = false; "
"let dialog, dialogMessage;"
"function init() {"
"colorWheel = document.getElementById(\"colorWheel\");"
"colorSelector = document.getElementById(\"colorSelector\");"
"currentColor = document.getElementById(\"currentColor\");"
"setColorBtn = document.getElementById(\"setColorBtn\");"
"dialog = document.getElementById(\"dialog\");"
"dialogMessage = document.getElementById(\"dialogMessage\");"
"canvas = colorWheel;"
"ctx = canvas.getContext(\"2d\");"
"redrawCanvas();"
"window.addEventListener(\"resize\", redrawCanvas); "
"colorWheel.addEventListener(\"mousedown\", startDrag);"
"colorWheel.addEventListener(\"touchstart\", startDrag, { passive: true });"
"document.addEventListener(\"mousemove\", drag);"
"document.addEventListener(\"touchmove\", drag, { passive: false });"
"document.addEventListener(\"mouseup\", endDrag);"
"document.addEventListener(\"touchend\", endDrag);"
"setColorBtn.addEventListener(\"click\", setColor);"
"getColor();"
"}"
"function redrawCanvas() {"
"const container = colorWheel.parentElement;"
"const size = container.clientWidth;"
"canvas.width = size;"
"canvas.height = size;"
"centerX = size / 2; "
"centerY = size / 2; "
"radius = size / 2 - 5; "
"drawColorWheel();"
"}"
"function drawColorWheel() {"
"const gradient = ctx.createConicGradient(0, centerX, centerY); "
"gradient.addColorStop(0, \"#ff0000\"); "
"gradient.addColorStop(1 / 6, \"#ffff00\"); "
"gradient.addColorStop(2 / 6, \"#00ff00\"); "
"gradient.addColorStop(3 / 6, \"#00ffff\"); "
"gradient.addColorStop(4 / 6, \"#0000ff\"); "
"gradient.addColorStop(5 / 6, \"#ff00ff\"); "
"gradient.addColorStop(1, \"#ff0000\"); "
"ctx.beginPath();"
"ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI);"
"ctx.fillStyle = gradient;"
"ctx.fill();"
"const innerRadius = radius * 0.8;"
"const innerGradient = ctx.createRadialGradient("
"centerX,"
"centerY,"
"0,"
"centerX,"
"centerY,"
"innerRadius"
");"
"innerGradient.addColorStop(0, \"#ffffff\");"
"innerGradient.addColorStop(1, \"rgba(255, 255, 255, 0)\");"
"ctx.beginPath();"
"ctx.arc(centerX, centerY, innerRadius, 0, 2 * Math.PI);"
"ctx.fillStyle = innerGradient;"
"ctx.fill();"
"}"
"function startDrag(e) {"
"e.preventDefault(); "
"isDragging = true; "
"moveSelector(e); "
"}"
"function drag(e) {"
"if (isDragging) {"
"e.preventDefault(); "
"moveSelector(e); "
"}"
"}"
"function endDrag() {"
"isDragging = false; "
"}"
"function moveSelector(e) {"
"let clientX, clientY;"
"if (e.type.includes(\"mouse\")) {"
"clientX = e.clientX;"
"clientY = e.clientY;"
"} else {"
"clientX = e.touches[0].clientX;"
"clientY = e.touches[0].clientY;"
"}"
"const rect = canvas.getBoundingClientRect();"
"const x = clientX - rect.left;"
"const y = clientY - rect.top;"
"const dx = x - centerX;"
"const dy = y - centerY;"
"const distance = Math.sqrt(dx * dx + dy * dy);"
"let constrainedX = x;"
"let constrainedY = y;"
"const selectorRadius = 10;"
"if (distance > radius - selectorRadius) {"
"const ratio = (radius - selectorRadius) / distance;"
"constrainedX = centerX + dx * ratio;"
"constrainedY = centerY + dy * ratio;"
"}"
"colorSelector.style.left = `${constrainedX}px`;"
"colorSelector.style.top = `${constrainedY}px`;"
"updateCurrentColor(constrainedX, constrainedY);"
"}"
"function updateCurrentColor(x, y) {"
"const imageData = ctx.getImageData(x, y, 1, 1);"
"const pixel = imageData.data;"
"let r = pixel[0];"
"let g = pixel[1];"
"let b = pixel[2];"
"const threshold = 240; "
"if (r > threshold && g > threshold && b > threshold) {"
"const dx = x - centerX;"
"const dy = y - centerY;"
"const distance = Math.sqrt(dx * dx + dy * dy);"
"const innerRadius = radius * 0.8;"
"if (distance < innerRadius) {"
"const ratio = distance / innerRadius;"
"if (ratio < 0.3) {"
"r = 255;"
"g = 255;"
"b = 255;"
"} else {"
"r = Math.min(255, Math.max(0, r));"
"g = Math.min(255, Math.max(0, g));"
"b = Math.min(255, Math.max(0, b));"
"}"
"}"
"}"
"currentColor.style.backgroundColor = `rgb(${r}, ${g}, ${b})`;"
"currentColor.textContent = `RGB(${r}, ${g}, ${b})`;"
"return { r, g, b };"
"}"
"function findClosestColorPosition(targetR, targetG, targetB) {"
"const searchRadius = radius;"
"let bestMatch = null;"
"let minDifference = Infinity;"
"const step = 10;"
"for (let x = centerX - searchRadius; x <= centerX + searchRadius; x += step) {"
"for (let y = centerY - searchRadius; y <= centerY + searchRadius; y += step) {"
"const dx = x - centerX;"
"const dy = y - centerY;"
"const distance = Math.sqrt(dx * dx + dy * dy);"
"if (distance <= searchRadius) {"
"const imageData = ctx.getImageData(x, y, 1, 1);"
"const pixel = imageData.data;"
"const r = pixel[0];"
"const g = pixel[1];"
"const b = pixel[2];"
"const diff = Math.sqrt("
"Math.pow(r - targetR, 2) +"
"Math.pow(g - targetG, 2) +"
"Math.pow(b - targetB, 2)"
");"
"if (diff < minDifference) {"
"minDifference = diff;"
"bestMatch = { x, y, r, g, b, diff };"
"}"
"}"
"}"
"}"
"return bestMatch;"
"}"
"function setSelectorPositionByColor(r, g, b) {"
"const closest = findClosestColorPosition(r, g, b);"
"if (closest) {"
"x = closest.x;"
"y = closest.y;"
"console.log("
"`找到更接近的颜色位置: x=${x.toFixed(2)}, y=${y.toFixed("
"2"
")}, 差异=${closest.diff.toFixed(2)}`"
");"
"}"
"colorSelector.style.left = `${x}px`;"
"colorSelector.style.top = `${y}px`;"
"updateCurrentColor(x, y);"
"}"
"async function setColor() {"
"dialogMessage.textContent = \"改变颜色中...\";"
"dialog.showModal(); "
"const x = parseFloat(colorSelector.style.left);"
"const y = parseFloat(colorSelector.style.top);"
"const { r, g, b } = updateCurrentColor(x, y);"
"try {"
"const response = await fetch("
"`http://${deviceAddress}/set-color?r=${r}&g=${g}&b=${b}`,"
"{"
"method: \"POST\","
"}"
");"
"if (response.ok) {"
"dialogMessage.textContent = `设置成功`;"
"} else {"
"throw new Error(\"设置颜色失败\");"
"}"
"} catch (error) {"
"dialog.close(); "
"dialogMessage.textContent = error.message;"
"dialog.showModal(); "
"} finally {"
"setTimeout(() => {"
"dialog.close(); "
"}, 1000);"
"}"
"}"
"async function getColor() {"
"dialogMessage.textContent = \"获取颜色中...\";"
"dialog.showModal(); "
"try {"
"const response = await fetch(`http://${deviceAddress}/current-color`, {});"
"if (response.ok) {"
"dialogMessage.textContent = `获取成功`;"
"const text = await response.text();"
"const colorValues = text.split(\",\");"
"const r = parseInt(colorValues[0]);"
"const g = parseInt(colorValues[1]);"
"const b = parseInt(colorValues[2]);"
"updateCurrentColor(r, g, b);"
"setSelectorPositionByColor(r, g, b);"
"} else {"
"throw new Error(\"获取颜色失败\");"
"}"
"} catch (error) {"
"dialog.close(); "
"dialogMessage.textContent = error.message;"
"dialog.showModal(); "
"setTimeout(() => {"
"dialog.close(); "
"}, 1000);"
"} finally {"
"dialog.close(); "
"}"
"}"
"window.addEventListener(\"load\", init);"
"</script>"
"</body>"
"</html>";