const char *page = "<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset=\"utf-8\" />"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />"
"<title>Magic-Mini</title>"
"<style>"
"html,"
"body {height: 100%; margin: 0;}"
"body {font-family: Arial, Helvetica, sans-serif; background: #fff; display: flex; justify-content: center; align-items: flex-start;}"
".wrap {width: 100%; max-width: 420px; display: flex; flex-direction: column; align-items: center; box-sizing: border-box; padding-top: 60px; padding-left: 16px; padding-right: 16px;}"
"h1 {font-size: 42px; margin: 0 0 40px 0; text-align: center; color: #222;}"
".btn {display: inline-block; padding: 12px 28px; font-size: 18px; text-decoration: none; color: #fff; border-radius: 6px; transition: all 0.3s; margin-bottom: 20px; opacity: 1;}"
".btn:hover {opacity: 0.9; transform: scale(0.99); transform:translateY(-2px);}"
"</style>"
"</head>"
"<body>"
"<div class=\"wrap\">"
"<h1>Magic-Mini</h1>"
"<a href=\"/color\" class=\"btn\" style=\"background-color: #007bff;\">调整颜色</a>"
"<a href=\"/ota\" class=\"btn\" style=\"background-color: #28a745;\">OTA升级</a>"
"</div>"
"</body>"
"</html>";